### ISSUE TITLE
A bit more info would be appreciated :-)

### ISSUE THREAD

**Issue by andypnz** [liqi0816/ble2mqtt#3]
Hi. This is a great addition to HA - the Adaprox fingerbots are really cheap :-)

I am using HAOS. I have not run any Python in HA - should this run under something like AppDaemon?

And can the script to get the device id, etc - can that be run under HA? Or do you need a separate Python environment to run it under (like a Linux box / VM / etc)?

**Comment by liqi0816** [comment]
Hi,

This is a standalone program and does not depend on AppDaemon. In fact we are not using any HA python API at all. The program interacts with HASS just like [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt). Everything is done via mqtt.

Sorry but I don't quite understand your second question. This program sends the desired device id to HA via mqtt. On HAOS python should be preinstalled, and it should be fine to just use that installation. For MQTT there is an [addon](https://my.home-assistant.io/redirect/supervisor_addon/?addon=core_mosquitto).

I chose to write a standalone program because it's easier to restart a small program than the entire HASS.

**Comment by andypnz** [comment]
Thanks... I think I need a Tuya hub, right? 

Or will this work direct to the fingerbot via RPi BT?

**Comment by liqi0816** [comment]
You don't need a Tuya Hub. The purpose of this program is to use conventional bluetooth adapters, and to work completely offline.

If you have a Tuya Hub, you can use the official HA integration.

I'm using an [HP T630 from ebay](https://www.ebay.com/itm/285189052798) which is just a generic linux box. I don't have a RPi on hand, but it should also work as a generic linux box.

**Comment by andypnz** [comment]
Thanks for your help!
I have registered with Tuya Smart Life + Tuya iot platform.... and successfully run tuya-local-key-extractor (I was able to do this within my HAOS using SSH + Web Terminal) - so I have the required keys, ID and MAC address etc 

Which directory do I copy your fingerbot.py + util.py to? Are these the only files I need from your github repo?

What triggers fingerbot.py to run?

Thanks again for your help!

**Comment by liqi0816** [comment]
If you just want to integrate with HA, and don't want to bother with details like "what triggers fingerbot.py to run", my suggestion would be:

1. The [HA bluetooth requirements for Linux systems](https://www.home-assistant.io/integrations/bluetooth) still apply. For HAOS it means upgrading to version 9.0 or later.
2. install MQTT [addon](https://my.home-assistant.io/redirect/supervisor_addon/?addon=core_mosquitto). There are plenty of tutorial online, such as [this one](https://learn.adafruit.com/set-up-home-assistant-with-a-raspberry-pi/mqtt-setup).
3. SSH into HAOS, install the python dependencies listed in [README](https://github.com/liqi0816/ble2mqtt).
4. Clone the repository to any directory you like. It's a standalone program so it doesn't really matter.
5. Write config.yaml, save it to anywhere
   ```yaml
   homeassistant: true
   mqtt:
    base_topic: homeassistant
    server: mqtt://HAOS_IP_ADDRESS:1883
    user: SAME_AS_IN_HAOS_MQTT_ADDON
    password: SAME_AS_IN_HAOS_MQTT_ADDON
   controller:
    capacity: 6
   devices:
    '01:02:03:04:05:08':
      type: tuya.fingerbot
      device_id: abc123456
      uuid: tuya1234567890
      local_key: abc123456
      down_percent: 80
   ```
6. cd into ble2mqtt, then `python main.py --config [path-to-config.yaml]`

On success it should print
```
bluetooth.Client.event.connect 01:02:03:04:05:08
initialized with 1 devices
(after a while; Tuya devices go to sleep very fast) bluetooth.Client.event.disconnect 01:02:03:04:05:08
```

And a button device should be auto discovered in HA.
